// src/components/App.vue
<template>
  <v-app>
    <v-main class="fill-height">
      <v-container fluid>
        <div class="d-flex">
          <div class="mr-5">
            <v-switch
              v-model="enabledTypes"
              label="Guest"
              value="guest"
              dense
              class="mt-0"
            />
            <v-switch
              v-model="enabledTypes"
              label="Member"
              value="member"
              dense
              class="mt-0"
            />
            <v-switch
              v-model="enabledTypes"
              label="Moderator"
              value="moderator"
              dense
              class="mt-0"
            />
            <v-switch
              v-model="enabledTypes"
              label="Owner"
              value="owner"
              dense
              class="mt-0"
            />
          </div>
          <div>
            <v-switch
              v-model="enabledTypes"
              label="Super Chat"
              value="super-chat"
              dense
              class="mt-0"
            />
            <v-switch
              v-model="enabledTypes"
              label="Super Sticker"
              value="super-sticker"
              dense
              class="mt-0"
            />
            <v-switch
              v-model="enabledTypes"
              label="Membership"
              value="membership"
              dense
              class="mt-0"
            />
          </div>
        </div>
        <v-btn depressed small block @click="handleClickReset"> Reset </v-btn>
      </v-container>
    </v-main>
  </v-app>
</template>

<script lang="ts">
import { defineComponent, computed } from '@vue/composition-api'
import { AuthorType, Types } from '~/models'
import { settingsStore } from '~/store'

export default defineComponent({
  setup() {
    const enabledTypes = computed({
      get: () => {
        return Object.keys(settingsStore.types).filter(
          (type) => settingsStore.types[type as AuthorType]
        )
      },
      set: (value) => {
        const types = Object.keys(settingsStore.types).reduce((carry, type) => {
          return {
            ...carry,
            [type]: value.includes(type),
          }
        }, {} as Types)
        settingsStore.setTypes({ types })
      },
    })

    const handleClickReset = () => {
      settingsStore.reset()
    }

    return {
      enabledTypes,
      handleClickReset,
    }
  },
})
</script>

<style lang="scss">
html {
  overflow-y: hidden;
}
</style>

<style lang="scss" scoped>
.v-application {
  min-width: 320px;
}
</style>

// src/components/App.tsx
import {
  Box,
  Button,
  CssBaseline,
  FormControlLabel,
  FormGroup,
  GlobalStyles,
  Switch,
} from '@mui/material'
import { ChangeEvent } from 'react'
import { StoreProvider } from '~/contexts/StoreContext'
import { useAppDispatch, useAppSelector } from '~/store'
import { reset, selectTypes, setTypes } from '~/store/settings'

const InnerApp = () => {
  const types = useAppSelector(selectTypes)
  const dispatch = useAppDispatch()

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    const { checked, value } = e.currentTarget
    dispatch(setTypes({ ...types, [value]: checked }))
  }

  const handleClickReset = () => dispatch(reset())

  return (
    <Box sx={{ m: 1 }}>
      <FormGroup sx={{ flexDirection: 'row', mx: 1 }}>
        <Box sx={{ display: 'flex', flexDirection: 'column' }}>
          <FormControlLabel
            control={
              <Switch
                checked={types.guest}
                onChange={handleChange}
                value="guest"
              />
            }
            label="Guest"
          />
          <FormControlLabel
            control={
              <Switch
                checked={types.member}
                onChange={handleChange}
                value="member"
              />
            }
            label="Member"
          />
          <FormControlLabel
            control={
              <Switch
                checked={types.moderator}
                onChange={handleChange}
                value="moderator"
              />
            }
            label="Moderator"
          />
          <FormControlLabel
            control={
              <Switch
                checked={types.owner}
                onChange={handleChange}
                value="owner"
              />
            }
            label="Owner"
          />
        </Box>
        <Box sx={{ display: 'flex', flexDirection: 'column' }}>
          <FormControlLabel
            control={
              <Switch
                checked={types['super-chat']}
                onChange={handleChange}
                value="super-chat"
              />
            }
            label="Super Chat"
          />
          <FormControlLabel
            control={
              <Switch
                checked={types['super-sticker']}
                onChange={handleChange}
                value="super-sticker"
              />
            }
            label="Super Sticker"
          />
          <FormControlLabel
            control={
              <Switch
                checked={types.membership}
                onChange={handleChange}
                value="membership"
              />
            }
            label="Membership"
          />
        </Box>
      </FormGroup>
      <Button fullWidth onClick={handleClickReset} size="small">
        Reset
      </Button>
    </Box>
  )
}

const App = () => {
  return (
    <StoreProvider>
      <CssBaseline />
      <GlobalStyles
        styles={{
          html: { overflowY: 'hidden', width: 330 },
        }}
      />
      <InnerApp />
    </StoreProvider>
  )
}

export default App
